baseURL = 'https://lucabrunox.github.io/'
languageCode = 'en-us'
title = 'Luca Bruno blog'
publishDir = "docs"
theme = "paper"

[params]
color='linen'
linkedin='lucabrunox'
github='lucabrunox'
monoDarkIcon=true

